// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    copy: typeof import('./src/components/sidebar copy.vue')['default']
    ElAvatar: typeof import('element-plus/lib')['ElAvatar']
    ElButtom: typeof import('element-plus/lib')['ElButtom']
    ElButton: typeof import('element-plus/lib')['ElButton']
    ElCard: typeof import('element-plus/lib')['ElCard']
    ElCascader: typeof import('element-plus/lib')['ElCascader']
    ElCheckbox: typeof import('element-plus/lib')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/lib')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/lib')['ElCol']
    ElDatePick: typeof import('element-plus/lib')['ElDatePick']
    ElDatePicker: typeof import('element-plus/lib')['ElDatePicker']
    ElDialog: typeof import('element-plus/lib')['ElDialog']
    ElDropdown: typeof import('element-plus/lib')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/lib')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/lib')['ElDropdownMenu']
    ElForm: typeof import('element-plus/lib')['ElForm']
    ElFormItem: typeof import('element-plus/lib')['ElFormItem']
    ElIcon: typeof import('element-plus/lib')['ElIcon']
    ElImage: typeof import('element-plus/lib')['ElImage']
    ElInput: typeof import('element-plus/lib')['ElInput']
    ElMenu: typeof import('element-plus/lib')['ElMenu']
    ElMenuItem: typeof import('element-plus/lib')['ElMenuItem']
    ElOption: typeof import('element-plus/lib')['ElOption']
    ElPagination: typeof import('element-plus/lib')['ElPagination']
    ElProgress: typeof import('element-plus/lib')['ElProgress']
    ElRadio: typeof import('element-plus/lib')['ElRadio']
    ElRadioGroup: typeof import('element-plus/lib')['ElRadioGroup']
    ElRow: typeof import('element-plus/lib')['ElRow']
    ElSelect: typeof import('element-plus/lib')['ElSelect']
    ElSetect: typeof import('element-plus/lib')['ElSetect']
    ElSubMenu: typeof import('element-plus/lib')['ElSubMenu']
    ElSwitch: typeof import('element-plus/lib')['ElSwitch']
    ElTable: typeof import('element-plus/lib')['ElTable']
    ElTableColumn: typeof import('element-plus/lib')['ElTableColumn']
    ElTabPane: typeof import('element-plus/lib')['ElTabPane']
    ElTabs: typeof import('element-plus/lib')['ElTabs']
    ElTag: typeof import('element-plus/lib')['ElTag']
    ElTimePicker: typeof import('element-plus/lib')['ElTimePicker']
    ElTooltip: typeof import('element-plus/lib')['ElTooltip']
    ElUpload: typeof import('element-plus/lib')['ElUpload']
    Header: typeof import('./src/components/header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/sidebar.vue')['default']
    Tags: typeof import('./src/components/tags.vue')['default']
  }
}
